//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.PushMenu.Web.layouts.SitecorePushMenu.Sublayouts
{


    public partial class PushMenu
    {
    }
}
